// Generated by CIRCT firtool-1.114.1
module ALU(
  input  [31:0] io_in_a,
                io_in_b,
  input         io_in_sub,
                io_in_sign,
  input  [2:0]  io_in_aluType,
  output [31:0] io_out_result,
                io_out_add_result,
  output        io_out_cmp
);

  wire             io_out_cmp_0;
  wire [32:0]      _sum_T_1 = {1'h0, io_in_a} + {1'h0, io_in_b} + {32'h0, io_in_sub};
  wire [62:0]      sll = {31'h0, io_in_a} << io_in_b[4:0];
  wire [31:0]      _GEN = {27'h0, io_in_b[4:0]};
  wire [7:0][31:0] _GEN_0 =
    {{io_in_a & io_in_b},
     {io_in_a | io_in_b},
     {$signed($signed(io_in_a) >>> _GEN)},
     {io_in_a >> _GEN},
     {io_in_a ^ io_in_b},
     {{{31{io_in_a[31]}}, io_out_cmp_0}},
     {sll[31:0]},
     {_sum_T_1[31:0]}};
  assign io_out_cmp_0 =
    io_in_sign
      ? io_in_a[31] & io_in_b[31] | _sum_T_1[31] & (io_in_a[31] ^ io_in_b[31])
      : ~(_sum_T_1[32]);
  assign io_out_result = _GEN_0[io_in_aluType];
  assign io_out_add_result = _sum_T_1[31:0];
  assign io_out_cmp = io_out_cmp_0;
endmodule

