// Generated by CIRCT firtool-1.114.1

    module DpiIFU(
      input reset,
      input [31:0] pc,
      output logic [31:0] inst
    );
      import "DPI-C" function int fetch_inst(input int pc);

      always @(pc) begin
        if(!reset) inst = fetch_inst(pc);
      end
    endmodule
    