// Generated by CIRCT firtool-1.114.1

    module DpiMem(
      input        wen,
      input        ren,
      input [31:0] addr,
      input [31:0] wdata,
      output logic [31:0] rdata,
      input [3:0]  wmask
    );
      import "DPI-C" function int pmem_read(input int raddr);
      import "DPI-C" function void pmem_write(input int waddr, input int wdata, input byte wmask);

      always @(ren or addr) begin
        if (ren) begin
          rdata = pmem_read(addr);
        end
      end

      always @(wen or addr or wdata or wmask) begin
        if (wen) begin
          pmem_write(addr, wdata, wmask);
        end
      end
    endmodule
    