// Generated by CIRCT firtool-1.114.1
module EXU(
  input  [3:0]  io_instType,
  input  [2:0]  io_func,
  input  [31:0] io_dataIO_pc,
                io_dataIO_rs1,
                io_dataIO_rs2,
                io_dataIO_imm,
                io_aluIn_a,
                io_aluIn_b,
  input         io_aluIn_sub,
                io_aluIn_sign,
  input  [2:0]  io_aluIn_aluType,
  output [31:0] io_result,
  output        io_jump,
  output [31:0] io_upc,
  output        io_resultType,
                io_lsuIO_wen,
                io_lsuIO_ren,
  output [31:0] io_lsuIO_addr,
                io_lsuIO_wdata,
  output [3:0]  io_lsuIO_wmask,
  output [2:0]  io_lsuIO_read_type,
  output        io_regWen
);

  wire _alu_io_out_cmp;
  wire _io_upc_T = io_instType == 4'h7;
  wire io_lsuIO_wen_0 = io_instType == 4'h2;
  wire _is_bge_T = io_instType == 4'h3;
  wire io_resultType_0 = io_instType == 4'h5;
  ALU alu (
    .io_in_a           (io_aluIn_a),
    .io_in_b           (io_aluIn_b),
    .io_in_sub         (io_aluIn_sub),
    .io_in_sign        (io_aluIn_sign),
    .io_in_aluType     (io_aluIn_aluType),
    .io_out_result     (io_result),
    .io_out_add_result (io_lsuIO_addr),
    .io_out_cmp        (_alu_io_out_cmp)
  );
  assign io_jump =
    io_instType == 4'h6 | _io_upc_T | _is_bge_T & ~(|io_func)
    & io_dataIO_rs1 == io_dataIO_rs2 | _is_bge_T & io_func == 3'h1
    & io_dataIO_rs1 != io_dataIO_rs2 | _is_bge_T & (io_func == 3'h4 | io_func == 3'h6)
    & _alu_io_out_cmp | _is_bge_T & (io_func == 3'h5 | (&io_func)) & ~_alu_io_out_cmp;
  assign io_upc = (_io_upc_T ? io_dataIO_rs1 : io_dataIO_pc) + io_dataIO_imm;
  assign io_resultType = io_resultType_0;
  assign io_lsuIO_wen = io_lsuIO_wen_0;
  assign io_lsuIO_ren = io_resultType_0;
  assign io_lsuIO_wdata = io_dataIO_rs2;
  assign io_lsuIO_wmask =
    io_lsuIO_wen_0 ? ((|io_func) ? (io_func == 3'h1 ? 4'h3 : 4'hF) : 4'h1) : 4'h0;
  assign io_lsuIO_read_type = io_func;
  assign io_regWen = ~(io_lsuIO_wen_0 | _is_bge_T);
endmodule

