// Generated by CIRCT firtool-1.114.1
module IDU(
  input  [31:0] io_inst,
  output [3:0]  io_instType,
  output [2:0]  io_func,
  output [4:0]  io_raddrIO_raddr_0,
                io_raddrIO_raddr_1,
                io_rd,
  output [31:0] io_imm
);

  wire [3:0] instType =
    io_inst[6:0] == 7'h33
      ? 4'h0
      : io_inst[6:0] == 7'h13
          ? 4'h1
          : io_inst[6:0] == 7'h3
              ? 4'h5
              : io_inst[6:0] == 7'h67
                  ? 4'h7
                  : io_inst[6:0] == 7'h23
                      ? 4'h2
                      : io_inst[6:0] == 7'h63
                          ? 4'h3
                          : io_inst[6:0] == 7'h37
                              ? 4'h8
                              : io_inst[6:0] == 7'h17
                                  ? 4'h9
                                  : io_inst[6:0] == 7'h73
                                      ? 4'hA
                                      : io_inst[6:0] == 7'hF
                                          ? 4'hB
                                          : io_inst[6:0] == 7'h6F ? 4'h6 : 4'h0;
  ImmGen immGen (
    .io_inst     (io_inst),
    .io_instType (instType),
    .io_imm      (io_imm)
  );
  QUIT quit (
    .is_quit (io_inst == 32'h100073)
  );
  assign io_instType = instType;
  assign io_func = io_inst[14:12];
  assign io_raddrIO_raddr_0 = io_inst[19:15];
  assign io_raddrIO_raddr_1 = io_inst[24:20];
  assign io_rd = io_inst[11:7];
endmodule

