// Generated by CIRCT firtool-1.114.1
module IFU(
  input         clock,
                reset,
  input  [31:0] io_upc,
  input         io_jump,
  output [31:0] io_inst,
                io_pc
);

  reg [31:0] pc;
  always @(posedge clock) begin
    if (reset)
      pc <= 32'h80000000;
    else
      pc <= io_jump ? io_upc : pc + 32'h4;
  end // always @(posedge)
  DpiIFU ifu (
    .pc    (pc),
    .inst  (io_inst),
    .reset (reset)
  );
  assign io_pc = pc;
endmodule

