// Generated by CIRCT firtool-1.114.1
module ImmGen(
  input  [31:0] io_inst,
  input  [3:0]  io_instType,
  output [31:0] io_imm
);

  assign io_imm =
    io_instType == 4'h1 | io_instType == 4'h5 | io_instType == 4'h7
      ? {{20{io_inst[31]}}, io_inst[31:20]}
      : io_instType == 4'h8 | io_instType == 4'h9
          ? {io_inst[31:12], 12'h0}
          : io_instType == 4'h2
              ? {{20{io_inst[31]}}, io_inst[31:25], io_inst[11:7]}
              : io_instType == 4'h3
                  ? {{20{io_inst[31]}}, io_inst[7], io_inst[30:25], io_inst[11:8], 1'h0}
                  : io_instType == 4'h6
                      ? {{12{io_inst[31]}},
                         io_inst[19:12],
                         io_inst[20],
                         io_inst[30:21],
                         1'h0}
                      : io_instType == 4'h0 ? {25'h0, io_inst[31:25]} : 32'h0;
endmodule

