// Generated by CIRCT firtool-1.114.1
module LSU(
  input         io_lsuIO_wen,
                io_lsuIO_ren,
  input  [31:0] io_lsuIO_addr,
                io_lsuIO_wdata,
  input  [3:0]  io_lsuIO_wmask,
  input  [2:0]  io_lsuIO_read_type,
  output [31:0] io_rdata
);

  wire [31:0]      _mem_rdata;
  wire [3:0][31:0] _GEN =
    {{{24'h0, _mem_rdata[31:24]}},
     {{16'h0, _mem_rdata[31:16]}},
     {{8'h0, _mem_rdata[31:8]}},
     {_mem_rdata}};
  wire [31:0]      rdata_aligned = _GEN[io_lsuIO_addr[1:0]];
  wire [7:0][31:0] _GEN_0 =
    {{32'h0},
     {32'h0},
     {{16'h0, rdata_aligned[15:0]}},
     {{24'h0, rdata_aligned[7:0]}},
     {32'h0},
     {rdata_aligned},
     {{{16{rdata_aligned[15]}}, rdata_aligned[15:0]}},
     {{{24{rdata_aligned[7]}}, rdata_aligned[7:0]}}};
  DpiMem mem (
    .wen   (io_lsuIO_wen),
    .ren   (io_lsuIO_ren),
    .addr  (io_lsuIO_addr),
    .wdata (io_lsuIO_wdata),
    .rdata (_mem_rdata),
    .wmask (io_lsuIO_wmask)
  );
  assign io_rdata = _GEN_0[io_lsuIO_read_type];
endmodule

