// Generated by CIRCT firtool-1.114.1
module OpSel(
  input  [3:0]  io_instType,
  input  [2:0]  io_func,
  input  [31:0] io_dataIO_pc,
                io_dataIO_rs1,
                io_dataIO_rs2,
                io_dataIO_imm,
  output [31:0] io_aluIO_a,
                io_aluIO_b,
  output        io_aluIO_sub,
                io_aluIO_sign,
  output [2:0]  io_aluIO_aluType
);

  wire       f010 = io_func == 3'h2;
  wire       f100 = io_func == 3'h4;
  wire       f101 = io_func == 3'h5;
  wire       f110 = io_func == 3'h6;
  wire       _GEN = io_instType == 4'h8;
  wire       _GEN_0 = io_instType == 4'h6;
  wire       _GEN_1 = io_instType == 4'h7;
  wire       _GEN_2 = io_instType == 4'h9;
  wire       _GEN_3 = io_instType == 4'h1;
  wire       _GEN_4 = io_instType == 4'h0;
  wire       _GEN_5 = f010 | io_func == 3'h3;
  wire       _GEN_6 = io_instType == 4'h3;
  wire       sub_sel =
    _GEN_4 ? _GEN_5 | io_func == 3'h0 & io_dataIO_imm[5] : _GEN_3 ? _GEN_5 : _GEN_6;
  wire [2:0] _GEN_7 = f100 ? 3'h3 : _GEN_5 ? 3'h2 : {2'h0, io_func == 3'h1};
  assign io_aluIO_a =
    _GEN ? 32'h0 : _GEN_0 | _GEN_1 | _GEN_2 ? io_dataIO_pc : io_dataIO_rs1;
  assign io_aluIO_b =
    {32{sub_sel}}
    ^ (_GEN_3 | io_instType == 4'h5 | io_instType == 4'h2 | _GEN | _GEN_2
         ? io_dataIO_imm
         : _GEN_0 | _GEN_1 ? 32'h4 : io_dataIO_rs2);
  assign io_aluIO_sub = sub_sel;
  assign io_aluIO_sign = _GEN_4 ? f010 : _GEN_6 & (f100 | f101);
  assign io_aluIO_aluType =
    _GEN_4
      ? ((&io_func) ? 3'h7 : f110 ? 3'h6 : f101 ? {2'h2, io_dataIO_imm[5]} : _GEN_7)
      : _GEN_3
          ? ((&io_func) ? 3'h7 : f110 ? 3'h6 : f101 ? {2'h2, io_dataIO_imm[10]} : _GEN_7)
          : 3'h0;
endmodule

