// Generated by CIRCT firtool-1.114.1

    module QUIT(
      input is_quit
    );
      import "DPI-C" function void quit();
      always_comb begin
        if(is_quit) quit();
      end
    endmodule
    