// Generated by CIRCT firtool-1.114.1
module top(
  input clock,
        reset
);

  wire [31:0] _regfile_io_rdataIO_rdata_0;
  wire [31:0] _regfile_io_rdataIO_rdata_1;
  wire [31:0] _lsu_io_rdata;
  wire [31:0] _exu_io_result;
  wire        _exu_io_jump;
  wire [31:0] _exu_io_upc;
  wire        _exu_io_resultType;
  wire        _exu_io_lsuIO_wen;
  wire        _exu_io_lsuIO_ren;
  wire [31:0] _exu_io_lsuIO_addr;
  wire [31:0] _exu_io_lsuIO_wdata;
  wire [3:0]  _exu_io_lsuIO_wmask;
  wire [2:0]  _exu_io_lsuIO_read_type;
  wire        _exu_io_regWen;
  wire [31:0] _opSel_io_aluIO_a;
  wire [31:0] _opSel_io_aluIO_b;
  wire        _opSel_io_aluIO_sub;
  wire        _opSel_io_aluIO_sign;
  wire [2:0]  _opSel_io_aluIO_aluType;
  wire [3:0]  _idu_io_instType;
  wire [2:0]  _idu_io_func;
  wire [4:0]  _idu_io_raddrIO_raddr_0;
  wire [4:0]  _idu_io_raddrIO_raddr_1;
  wire [4:0]  _idu_io_rd;
  wire [31:0] _idu_io_imm;
  wire [31:0] _ifu_io_inst;
  wire [31:0] _ifu_io_pc;
  IFU ifu (
    .clock   (clock),
    .reset   (reset),
    .io_upc  (_exu_io_upc),
    .io_jump (_exu_io_jump),
    .io_inst (_ifu_io_inst),
    .io_pc   (_ifu_io_pc)
  );
  IDU idu (
    .io_inst            (_ifu_io_inst),
    .io_instType        (_idu_io_instType),
    .io_func            (_idu_io_func),
    .io_raddrIO_raddr_0 (_idu_io_raddrIO_raddr_0),
    .io_raddrIO_raddr_1 (_idu_io_raddrIO_raddr_1),
    .io_rd              (_idu_io_rd),
    .io_imm             (_idu_io_imm)
  );
  OpSel opSel (
    .io_instType      (_idu_io_instType),
    .io_func          (_idu_io_func),
    .io_dataIO_pc     (_ifu_io_pc),
    .io_dataIO_rs1    (_regfile_io_rdataIO_rdata_0),
    .io_dataIO_rs2    (_regfile_io_rdataIO_rdata_1),
    .io_dataIO_imm    (_idu_io_imm),
    .io_aluIO_a       (_opSel_io_aluIO_a),
    .io_aluIO_b       (_opSel_io_aluIO_b),
    .io_aluIO_sub     (_opSel_io_aluIO_sub),
    .io_aluIO_sign    (_opSel_io_aluIO_sign),
    .io_aluIO_aluType (_opSel_io_aluIO_aluType)
  );
  EXU exu (
    .io_instType        (_idu_io_instType),
    .io_func            (_idu_io_func),
    .io_dataIO_pc       (_ifu_io_pc),
    .io_dataIO_rs1      (_regfile_io_rdataIO_rdata_0),
    .io_dataIO_rs2      (_regfile_io_rdataIO_rdata_1),
    .io_dataIO_imm      (_idu_io_imm),
    .io_aluIn_a         (_opSel_io_aluIO_a),
    .io_aluIn_b         (_opSel_io_aluIO_b),
    .io_aluIn_sub       (_opSel_io_aluIO_sub),
    .io_aluIn_sign      (_opSel_io_aluIO_sign),
    .io_aluIn_aluType   (_opSel_io_aluIO_aluType),
    .io_result          (_exu_io_result),
    .io_jump            (_exu_io_jump),
    .io_upc             (_exu_io_upc),
    .io_resultType      (_exu_io_resultType),
    .io_lsuIO_wen       (_exu_io_lsuIO_wen),
    .io_lsuIO_ren       (_exu_io_lsuIO_ren),
    .io_lsuIO_addr      (_exu_io_lsuIO_addr),
    .io_lsuIO_wdata     (_exu_io_lsuIO_wdata),
    .io_lsuIO_wmask     (_exu_io_lsuIO_wmask),
    .io_lsuIO_read_type (_exu_io_lsuIO_read_type),
    .io_regWen          (_exu_io_regWen)
  );
  LSU lsu (
    .io_lsuIO_wen       (_exu_io_lsuIO_wen),
    .io_lsuIO_ren       (_exu_io_lsuIO_ren),
    .io_lsuIO_addr      (_exu_io_lsuIO_addr),
    .io_lsuIO_wdata     (_exu_io_lsuIO_wdata),
    .io_lsuIO_wmask     (_exu_io_lsuIO_wmask),
    .io_lsuIO_read_type (_exu_io_lsuIO_read_type),
    .io_rdata           (_lsu_io_rdata)
  );
  RegFile regfile (
    .clock              (clock),
    .io_raddrIO_raddr_0 (_idu_io_raddrIO_raddr_0),
    .io_raddrIO_raddr_1 (_idu_io_raddrIO_raddr_1),
    .io_rdataIO_rdata_0 (_regfile_io_rdataIO_rdata_0),
    .io_rdataIO_rdata_1 (_regfile_io_rdataIO_rdata_1),
    .io_wIO_wen_0       (_exu_io_regWen),
    .io_wIO_wd_0        (_idu_io_rd),
    .io_wIO_wdata_0     (_exu_io_resultType ? _lsu_io_rdata : _exu_io_result)
  );
endmodule

